spring:
  application:
    name: taskcrud

  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
