spring:
  application:
    name: taskcrud
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com             # SMTP-сервер (в данном примере — Gmail)
    port: 587                        # Порт для TLS
    username: ser92012@gmail.com  # Твоя почта
    password: kagz sway jflk ddto     # Специальный пароль приложения (не обычный от Gmail)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
t1:
  scan-path: com.pr0maxx.taskcrud
  kafka:
    bootstrap:
      server: localhost:9092
    consumer:
      group-id: t1-demo
      max.poll.records: 10
    producer:
      enable: true
    topic:
      task_id_status_change: task-status-change-topic
    listener:
      poll-timeout: 1000